---
title: "tutorial_maybe"
output: html_document
date: "2024-04-22"
---

```{r}
library(psych)
library(lavaan)

install.packages("foreign")
install.packages("psych")
install.packages("GPArotation")

library(GPArotation) # package for factor analysis
library(foreign) # load spss data
library(psych)
library(dplyr)
```

```{r}
ex5_25 <- read.table("http://statmodel.com/usersguide/chap5/ex5.25.dat")
names(ex5_25) = paste0("y",1:12)

```

```{r}
normal_hearing_data <- read.csv("NH_DATA.csv")
hearing_impaired_data <- read.csv("HI_DATA.csv")
```
```{r}
all_data <- bind_rows(normal_hearing_data, hearing_impaired_data)
```

The efa for HI with two factors.
```{r}
var.names <- c("E1","E2","S3","E4","S5","S6","E7","S8", "E9", "S10")
fit <- efa(data = hearing_impaired_data[,var.names], nfactors = 1:2)
summary(fit)

```

Data 
```{r}
var.names <- c("E1","E2","S3","E4","S5","S6","E7","S8", "E9", "S10")
fit <- efa(data = hearing_impaired_data[,var.names], nfactors = 1:2)
summary(fit)

```

The efa for HI with three factors.
```{r}

var.names <- c("E1","E2","S3","E4","S5","S6","E7","S8", "E9", "S10")
fit_2 <- efa(data = hearing_impaired_data[,var.names], nfactors = 1:3)
summary(fit_2)

```

How to decide number of factors?
```{r}

correlation <- cor(fit_2)


```



